# Generated by Django 2.2.12 on 2020-09-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200927_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(blank=True, upload_to='auctions/img/'),
        ),
    ]
